### ISSUE TITLE
UnboundLocalError: local variable 'cond_cast_unet' referenced before assignment

### ISSUE THREAD

**Issue by Tahreezz** [lllyasviel/ControlNet#113]
I am having the following errors: what should I do?

`Traceback (most recent call last):
  File "D:\Stable\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\Stable\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Stable\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
    processed = process_images(p)
  File "D:\Stable\stable-diffusion-webui\modules\processing.py", line 487, in process_images
    res = process_images_inner(p)
  File "D:\Stable\stable-diffusion-webui\modules\processing.py", line 629, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "D:\Stable\stable-diffusion-webui\modules\processing.py", line 829, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\Stable\stable-diffusion-webui\modules\sd_samplers.py", line 544, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\Stable\stable-diffusion-webui\modules\sd_samplers.py", line 447, in launch_sampling
    return func()
  File "D:\Stable\stable-diffusion-webui\modules\sd_samplers.py", line 544, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\Stable\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Stable\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\Stable\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Stable\stable-diffusion-webui\modules\sd_samplers.py", line 337, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "D:\Stable\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Stable\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "D:\Stable\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "D:\Stable\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "D:\Stable\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "D:\Stable\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "D:\Stable\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Stable\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "D:\Stable\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Stable\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 147, in forward2
    return forward(*args, **kwargs)
  File "D:\Stable\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 112, in forward
    control = outer.control_model(x=x, hint=outer.hint_cond, timesteps=timesteps, context=context)
  File "D:\Stable\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Stable\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 425, in forward
    t_emb = cond_cast_unet(timestep_embedding(
UnboundLocalError: local variable 'cond_cast_unet' referenced before assignment`

**Comment by Mikubill** [comment]
try update your extension and restart webui

**Comment by Tahreezz** [comment]
doesn't work :')

> try update your extension and restart webui

**Comment by Mikubill** [comment]
Try reinstall the extension
