### ISSUE TITLE
Request: Integrate into pipeline assistance?

### ISSUE THREAD

**Issue by Baaleos** [lllyasviel/ControlNet#139]
I was wondering if someone could help me adapt the depth2img py script to work by taking an image path as opposed to numpy array from gradio.

My use case- I have a custom built discord bot that feeds requests into a db and then another program then calls the stable diffusion scripts based of a queue system. Essentially - I want to get depth2img without having to use the web-interface of gradio.

I've had a go at creating my own depth2img.py process method
It does seem to load the image from a path, but it then fails inside the ddim_sampler.sample call.
I had to load the image and then pack it into a numpy array - which is probably too simplistic to have worked tbh.

My code is here.

```
def process(input_image_path, prompt, a_prompt, n_prompt, num_samples, image_resolution, detect_resolution, ddim_steps, guess_mode, strength, scale, seed, eta):
    with torch.no_grad():
    
        assert os.path.isfile(input_image_path)
        #device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
        image_data = Image.open(input_image_path)
        input_image = asarray(image_data)
        input_image = HWC3(input_image)
        
        
        

        detected_map, _ = apply_midas(resize_image(input_image, detect_resolution))
        detected_map = HWC3(detected_map)
        img = resize_image(input_image, image_resolution)
        H, W, C = img.shape

        detected_map = cv2.resize(detected_map, (W, H), interpolation=cv2.INTER_LINEAR)

        control = torch.from_numpy(detected_map.copy()).float().cuda() / 255.0
        control = torch.stack([control for _ in range(num_samples)], dim=0)
        control = einops.rearrange(control, 'b h w c -> b c h w').clone()


        if seed == -1:
            seed = random.randint(0, 65535)
        seed_everything(seed)

        if config.save_memory:
            model.low_vram_shift(is_diffusing=False)

        cond = {"c_concat": [control], "c_crossattn": [model.get_learned_conditioning([prompt + ', ' + a_prompt] * num_samples)]}
        un_cond = {"c_concat": None if guess_mode else [control], "c_crossattn": [model.get_learned_conditioning([n_prompt] * num_samples)]}
        shape = (4, H // 8, W // 8)

        if config.save_memory:
            model.low_vram_shift(is_diffusing=True)

        model.control_scales = [strength * (0.825 ** float(12 - i)) for i in range(13)] if guess_mode else ([strength] * 13)  # Magic number. IDK why. Perhaps because 0.825**12<0.01 but 0.826**12>0.01
        
        print(prompt)
        print(a_prompt)
        print(n_prompt)
        print(num_samples)
        print(image_resolution)
        print(detect_resolution)
        print(ddim_steps)
        print(guess_mode)
        print(strength)
        print(scale)
        print(seed)
        print(eta)
        
        
        samples, intermediates = ddim_sampler.sample(ddim_steps, num_samples,
                                                     shape, cond, verbose=False, eta=eta,
                                                     unconditional_guidance_scale=scale,
                                                     unconditional_conditioning=un_cond)

        if config.save_memory:
            model.low_vram_shift(is_diffusing=False)

        x_samples = model.decode_first_stage(samples)
        x_samples = (einops.rearrange(x_samples, 'b c h w -> b h w c') * 127.5 + 127.5).cpu().numpy().clip(0, 255).astype(np.uint8)

        results = [x_samples[i] for i in range(num_samples)]
    return [detected_map] + results

```
The print messages are just debug messages- and they show that the arguments appear to be the correct type etc.
The error is below.

```
Data shape for DDIM sampling is (1, 4, 72, 72), eta 0.0
Running DDIM Sampling with 20 timesteps
DDIM Sampler:   0%|                                                                                        | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "depth2image.py", line 186, in <module>
    main()
  File "depth2image.py", line 183, in main
    process(opt.inputimage, opt.prompt, opt.added_prompt, opt.negative_prompt, 1, opt.resolution, opt.depthres, opt.steps, False, opt.controlstr, 9.0, opt.seed, 0.0)
  File "depth2image.py", line 99, in process
    samples, intermediates = ddim_sampler.sample(ddim_steps, num_samples,
  File "/home/baaleos/miniconda3/envs/control/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/baaleos/AIArtSetup/ControlNet/cldm/ddim_hacked.py", line 103, in sample
    samples, intermediates = self.ddim_sampling(conditioning, size,
  File "/home/baaleos/miniconda3/envs/control/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/baaleos/AIArtSetup/ControlNet/cldm/ddim_hacked.py", line 163, in ddim_sampling
    outs = self.p_sample_ddim(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
  File "/home/baaleos/miniconda3/envs/control/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/baaleos/AIArtSetup/ControlNet/cldm/ddim_hacked.py", line 190, in p_sample_ddim
    model_t = self.model.apply_model(x, t, c)
  File "/home/baaleos/AIArtSetup/ControlNet/cldm/cldm.py", line 338, in apply_model
    control = [c * scale for c, scale in zip(control, self.control_scales)]
  File "/home/baaleos/AIArtSetup/ControlNet/cldm/cldm.py", line 338, in <listcomp>
    control = [c * scale for c, scale in zip(control, self.control_scales)]
TypeError: only integer tensors of a single element can be converted to an index

```

**Comment by Baaleos** [comment]
closing - managed to resolve the issue- was due to arguments being passed in and parsed to the wrong data type.
