### ISSUE TITLE
logging improved.

### ISSUE THREAD

**Issue by aelmes** [lllyasviel/ControlNet#141]
Hello Team,

I can't launch app and below code in cmd:

logging improved.
No module 'xformers'. Proceeding without it.
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loaded model config from [./models/cldm_v15.yaml]
Traceback (most recent call last):
  File "gradio_scribble2image.py", line 18, in <module>
    model.load_state_dict(load_state_dict('./models/control_sd15_scribble.pth', location='cuda'))
  File "C:\Experiment\ControlNet\cldm\model.py", line 18, in load_state_dict
    state_dict = get_state_dict(torch.load(ckpt_path, map_location=torch.device(location)))
  File "C:\Users\Adda\.conda\envs\control\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Adda\.conda\envs\control\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Adda\.conda\envs\control\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './models/control_sd15_scribble.pth'

**Comment by yukistavailable** [comment]
You can download pre-trained models [here](https://huggingface.co/lllyasviel/ControlNet/tree/main/models).
