### ISSUE TITLE
I can't run controlnet on AUTOMATIC1111

### ISSUE THREAD

**Issue by vpuhoff** [lllyasviel/ControlNet#145]
https://huggingface.co/lllyasviel/ControlNet/blob/main/models/control_sd15_openpose.pth
![image](https://user-images.githubusercontent.com/2313869/220822229-10976dd3-1866-4df0-8664-2d2ed6fe7e1a.png)

python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.16.2  •  commit: [0cc0ee1b](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8)  •  checkpoint: [13dfc9921f](https://google.com/search?q=13dfc9921f8d0cc3fbf769edc3c3723c9db1aee3f85d0603fc45c7cba86d3397)

Error running process: P:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "P:\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "P:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 532, in process
    model_net.reset()
  File "P:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PlugableControlModel' object has no attribute 'reset'

**Comment by Mikubill** [comment]
Try fully restart WebUI
