### ISSUE TITLE
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:10801/')

### ISSUE THREAD

**Issue by tangyipeng100** [lllyasviel/ControlNet#182]
`python gradio_canny2image.py
logging improved.
Traceback (most recent call last):
  File "gradio_canny2image.py", line 6, in <module>
    import gradio as gr
...
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:10801/')
`
How to solve this problem in Ubuntu?

**Comment by eezywu** [comment]
> `python gradio_canny2image.py logging improved. Traceback (most recent call last): File "gradio_canny2image.py", line 6, in <module> import gradio as gr ... ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:10801/') ` How to solve this problem in Ubuntu?

you should close the network proxy in the system settings, and restart a new terminal to run the comand
