### ISSUE TITLE
Getting an error when using open pose

### ISSUE THREAD

**Issue by cyrilboh** [lllyasviel/ControlNet#186]
I'm just trying open pose for the first time in img2img.

Have uploaded an image to img2img.

Chosen a control image in ControlNet.

Chose openpose for preprocessor and control_openpose-fp16 [9ca67cc5] for the model.

I am getting the error as follows:

```
Loading model: control_openpose-fp16 [9ca67cc5]
Loaded state_dict from [C:\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\models\control_openpose-fp16.safetensors]
ControlNet model control_openpose-fp16 [9ca67cc5] loaded.
Loading preprocessor: openpose
Error running process: C:\local\sd\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\local\sd\stable-diffusion-webui-directml\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "C:\local\sd\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\controlnet.py", line 652, in process
    detected_map = preprocessor(input_image, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "C:\local\sd\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\processor.py", line 129, in openpose
    result, _ = model_openpose(img, has_hand)
  File "C:\local\sd\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 50, in apply_openpose
    candidate, subset = body_estimation(oriImg)
  File "C:\local\sd\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\openpose\body.py", line 57, in __call__
    heatmap = cv2.resize(heatmap, (0, 0), fx=stride, fy=stride, interpolation=cv2.INTER_CUBIC)
cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src data type = 23 is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
```

Any ideas what I could have done wrong?

**Comment by chris19299** [comment]
I have the same problem 
do you use AMD GPU ?

**Comment by chris19299** [comment]
> I have the same problem , using RT6800X
by adding the astype('float32'). It should work.
heatmap = cv2.resize(heatmap.astype('float32'), (0, 0), fx=stride, fy=stride, interpolation=cv2.INTER_CUBIC)

**Comment by Dforko** [comment]
> > I have the same problem , using RT6800X
> > by adding the astype('float32'). It should work.
> > heatmap = cv2.resize(heatmap.astype('float32'), (0, 0), fx=stride, fy=stride, interpolation=cv2.INTER_CUBIC)

Great, thank you Chris. In which file I need to add this?

**Comment by chris19299** [comment]
> > > I have the same problem , using RT6800X
> > > by adding the astype('float32'). It should work.
> > > heatmap = cv2.resize(heatmap.astype('float32'), (0, 0), fx=stride, fy=stride, interpolation=cv2.INTER_CUBIC)
> 
> Great, thank you Chris. In which file I need to add this? body.py? I'm just learning Python and not used to long error messages...

open file from  "openpose\body.py"

**Comment by Dforko** [comment]
Hi, thank you again for your response. I tried it and did not work. I even changed other  body.py and still broken...

**Comment by chris19299** [comment]
> Hi, thank you again for your response. I tried it and did not work. I even changed other body.py and still broken...

same error message ? 
I change the code as follow, you may take a reference 
 heatmap = cv2.resize(heatmap.astype('float32'), (0, 0), fx=stride, fy=stride, interpolation=cv2.INTER_CUBIC)
 paf = cv2.resize(paf.astype('float32'), (0, 0), fx=stride, fy=stride, interpolation=cv2.INTER_CUBIC)

**Comment by Dforko** [comment]
Yes!, I realized paf needed to be corrected too. Now I don't have error , but the annotator preview image it's just a black square, no stick pose..

**Comment by sa20001** [comment]
This fixed the problem for me too

> > Hi, thank you again for your response. I tried it and did not work. I even changed other body.py and still broken...
> 
> same error message ? I change the code as follow, you may take a reference heatmap = cv2.resize(heatmap.astype('float32'), (0, 0), fx=stride, fy=stride, interpolation=cv2.INTER_CUBIC) paf = cv2.resize(paf.astype('float32'), (0, 0), fx=stride, fy=stride, interpolation=cv2.INTER_CUBIC)
