### ISSUE TITLE
Getting this error after updating to latest version through SD webui extension interface.

### ISSUE THREAD

**Issue by NorTroll** [lllyasviel/ControlNet#208]
Loading preprocessor: canny
Error running process: G:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "G:\ai\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "G:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 691, in process
    forward_param = ControlParams(model_net, control, guess_mode, weight, False, guidance_start, guidance_end, None, isinstance(model_net, PlugableAdapter))
TypeError: ControlParams.__init__() takes 9 positional arguments but 10 were given

**Comment by NorTroll** [comment]
def process(self, p):
        for script in self.alwayson_scripts:
            try:
                script_args = p.script_args[script.args_from:script.args_to]
                script.process(p, *script_args) <--- this is line 386 in scripts.py
            except Exception:
                print(f"Error running process: {script.filename}", file=sys.stderr)
                print(traceback.format_exc(), file=sys.stderr)

**Comment by flaa2000** [comment]
Yes I just got this as well.

**Comment by thecord** [comment]
yup, same here :(
