### ISSUE TITLE
Can't get gradio app to load: pickle.UnpicklingError: invalid load key, 'v'

### ISSUE THREAD

**Issue by beaucarnes** [lllyasviel/ControlNet#22]
I'm having trouble getting the Gradio app to load. Most likely user error but I can't figure out my problem. I followed the instructions on the Readme. I downloaded the models and detectors from Huggingface and put them in the correct folders. But no matter what python file I try to run, I get a similar error. I'm trying on Windows 11.

Any ideas on what I'm doing wrong? Here is the error:

```
(control) C:\Users\BeauCarnes\Documents\ControlNet-main>python gradio_scribble2image.py
logging improved.
No module 'xformers'. Proceeding without it.
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loaded model config from [./models/cldm_v15.yaml]
Traceback (most recent call last):
  File "gradio_scribble2image.py", line 18, in <module>
    model.load_state_dict(load_state_dict('./models/control_sd15_scribble.pth', location='cpu'))
  File "C:\Users\BeauCarnes\Documents\ControlNet-main\cldm\model.py", line 18, in load_state_dict
    state_dict = get_state_dict(torch.load(ckpt_path, map_location=torch.device(location)))
  File "C:\Users\BeauCarnes\miniconda3\envs\control\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\BeauCarnes\miniconda3\envs\control\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by lllyasviel** [comment]
download control_sd15_scribble.pth again?

**Comment by JianbangZ** [comment]
Did you check to see if the model size is correct? Make sure you use git lfs instead of git

**Comment by beaucarnes** [comment]
Thanks. It is fixed now. I apparently didn't download the full model before and redownloading fixed the issue.
