### ISSUE TITLE
No such file or directory: './models/control_sd15_canny.pth'

### ISSUE THREAD

**Issue by aijiesd520** [lllyasviel/ControlNet#305]
logging improved.
No module 'xformers'. Proceeding without it.
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loaded model config from [./models/cldm_v15.yaml]
Traceback (most recent call last):
  File "gradio_canny2image.py", line 21, in <module>
    model.load_state_dict(load_state_dict('./models/control_sd15_canny.pth', location='cuda'))
  File "D:\Users\Administrator\Documents\GitHub\ControlNet\cldm\model.py", line 18, in load_state_dict
    state_dict = get_state_dict(torch.load(ckpt_path, map_location=torch.device(location)))
  File "C:\ProgramData\anaconda3\envs\control\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\ProgramData\anaconda3\envs\control\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\ProgramData\anaconda3\envs\control\lib\site-packages\torch\serialization.py", line 211, in __init__       
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './models/control_sd15_canny.pth'

**Comment by StudyingLover** [comment]
hello,di you resolve this problem? I also meet with this mistake and I have had this file.

**Comment by ArtoriaKawaii** [comment]
You can download pre-trained models [here](https://huggingface.co/lllyasviel/ControlNet/tree/main/models).

**Comment by StudyingLover** [comment]
ok,I konw what happend.I download in a floder and then I run bash `mv /path/to/control_sd15_canny.pth /path/to/ControlNet/models/control_sd15_canny.pth` ,but the file in /path/to/ControlNet/models is only a link not a real file
