### ISSUE TITLE
error on openpose after updating controlnet

### ISSUE THREAD

**Issue by sasukiss93** [lllyasviel/ControlNet#354]
Hello, i get this error when i use controlnet now.

I am using AMD GPU (rx 6900xt) on Windows.

I have been looking for several days and I can't find any solution, please help me.

```
Traceback (most recent call last):
  File "A:\Automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "A:\Automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "A:\Automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "A:\Automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "A:\Automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "A:\Automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "A:\Automatic1111\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\controlnet.py", line 398, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "A:\Automatic1111\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\processor.py", line 175, in openpose
    result = model_openpose(img)
  File "A:\Automatic1111\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 84, in __call__
    candidate, subset = self.body_estimation(oriImg)
  File "A:\Automatic1111\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\openpose\body.py", line 48, in __call__
    Mconv7_stage6_L1, Mconv7_stage6_L2 = self.model(data)
  File "A:\Automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "A:\Automatic1111\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\openpose\model.py", line 116, in forward
    out1 = self.model0(x)
  File "A:\Automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "A:\Automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "A:\Automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "A:\Automatic1111\stable-diffusion-webui-directml\extensions-builtin\Lora\lora.py", line 319, in lora_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lora(self, input)
  File "A:\Automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "A:\Automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (PrivateUse1FloatType) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
```

**Comment by thonsm06** [comment]
I'm get the same error with all of the openpose preprocessors.

6900xt, windows 10

**Comment by thonsm06** [comment]
Just tried again, this time a1111 downloaded a few openpose related .py files into the annotator folder. I thinks it's working.

**Comment by EricTsutola** [comment]
Yes this issue should be fixed now https://github.com/Mikubill/sd-webui-controlnet/issues/901#issue-1673736934
