### ISSUE TITLE
What is the reason for this? assert x.dtype == np.uint8

### ISSUE THREAD

**Issue by cdmusic2019** [lllyasviel/ControlNet#372]
Loading model from cache: control_v11p_sd15_inpaint [ebff9138]█████████████████████████| 34/34 [00:39<00:00,  1.15s/it]
Error running process: E:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "E:\ai\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "E:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 727, in process
    input_image = HWC3(np.asarray(p_input_image))
  File "E:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\util.py", line 6, in HWC3
    assert x.dtype == np.uint8
AssertionError

**Comment by engrmusawarali** [comment]
Change the color depth of image, The color depth must be 8.

**Comment by cdmusic2019** [comment]
> Change the color depth of image, The color depth must be 8.

Thank you. I think it's because I used the "segment-anything" plugin. The plugin is not perfect.
