### ISSUE TITLE
openpose not working after installing ControlNet 1.119

### ISSUE THREAD

**Issue by Yaandyy** [lllyasviel/ControlNet#387]
when setting preprocessor to openpose and model to control_v11p_sd15_openpose appears this error:

Error running process: E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "E:\AI\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1223, in process
    detected_map, is_image = preprocessor(input_image, res=preprocessor_resolution, thr_a=unit.threshold_a, thr_b=unit.threshold_b)
  File "E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 211, in run_model
    return self.model_openpose(
TypeError: OpenposeDetector.__call__() got an unexpected keyword argument 'json_pose_callback'

I've tried to find existing problem with this but failed to.

**Comment by Poopoopeepee42069** [comment]
I’m having a similar problem where controlnet won’t detect poses, it will return a void image. I saw that .150 is still able to detect poses. Is there a way to roll back to an earlier version?
