### ISSUE TITLE
Runtime Error: You have not selected any ControlNet model

### ISSUE THREAD

**Issue by AquatikJustice** [lllyasviel/ControlNet#401]
I'm getting the following error after updating to 1.1.166

`Error running process: G:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "G:\AI\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "G:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1022, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "G:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 685, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "G:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 694, in build_control_model
    raise RuntimeError(f"You have not selected any ControlNet Model.")
RuntimeError: You have not selected any ControlNet Model.`

This would normally make sense to me, however I'm trying to use the new "reference_only" preprocessor, which doesn't allow you to choose a CN model.

**Comment by Besamel** [comment]
I'm getting the same thing

**Comment by tonydaartista** [comment]
I'm getting the same thing too, anyone here would help?

**Comment by vanhapara** [comment]
The same :( need help

**Comment by vanhapara** [comment]
> The same :( need help

Found solution -> run Command Prompt under andministrator

**Comment by CaMMMXX** [comment]
I have also encountered it, delete all __pycache__ folders and files in the project root directory, restart, the problem can be solved

**Comment by birdddev** [comment]
A workaround for this seems to be enabling 'Allow preview' and 'Preview as Input'

CN 1.1.224 (Git hash: `0ddedce554ef5cf490b9196292feced91d882a5e`).

**Comment by zsychn** [comment]
> 
ERROR: This script must not be launched as root, aborting...  emmm

**Comment by LayerMaker** [comment]
> I'm getting the following error after updating to 1.1.166
> 
> `Error running process: G:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py Traceback (most recent call last): File "G:\AI\stable-diffusion-webui\modules\scripts.py", line 417, in process script.process(p, *script_args) File "G:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1022, in process model_net = self.load_control_model(p, unet, unit.model, unit.low_vram) File "G:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 685, in load_control_model model_net = self.build_control_model(p, unet, model, lowvram) File "G:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 694, in build_control_model raise RuntimeError(f"You have not selected any ControlNet Model.") RuntimeError: You have not selected any ControlNet Model.`
> 
> This would normally make sense to me, however I'm trying to use the new "reference_only" preprocessor, which doesn't allow you to choose a CN model.

I switched to "reference only" it incorporated my input image, and bypassed the " raise RuntimeError(f"You have not selected any ControlNet Model.")
    RuntimeError: You have not selected any ControlNet Model." but it is not finding the models that i placed in the CN models folder and essentially not working correctly, i removed all extensions other than CN for it to even allow me to have some influence from the input image

**Comment by love530love** [comment]
I kept having this problem when I was using edge, it was because edge didn't load the drop-down menu, then when I switched to Chrome, the drop-down box also appeared, and I could press the "Refresh" button next to it, Then in "Model" you can select "control_v11p_sd15_openpose [cab727d4]" model, after selecting this error will not appear. If the model doesn't exist, you may need to download it manually. Download it and place it in \stable-diffusion-webui\extensions\sd-webui-controlnet\models.
![image](https://github.com/lllyasviel/ControlNet/assets/92354089/a4043464-d00a-41ff-935c-a7d9f9a5dd3d)

**Comment by sunyuanxi** [comment]
I somehow solved this problem...? If you are using **multiple** ControlNet modules, **just take a look at your ControlNet Unit 1/2&3 etc, to see if they are also Enabled**. There currently is a bug I guess, that all these multiple ControlNet Units will be enabled together at first, which leads to the "not selecting model" error...

**Comment by haiduongarch** [comment]
Step 1:
Download models in: https://huggingface.co/lllyasviel/ControlNet-v1-1/tree/main
Step 2: Coppy pass in stable-diffusion-webui\models\ControlNet
C:\Users\XR\OneDrive\Máy tính\AI\SD\stable-diffusion-webui\models\ControlNet
Step 3: Apply and restar UI in Extensions on http://127.0.0.1:7862/
