### ISSUE TITLE
NameError: name 'apply_canny' is not defined

### ISSUE THREAD

**Issue by My12123** [lllyasviel/ControlNet#47]
(control) F:\ControlNet-main>python F:\ControlNet-main\gradio_canny2image.py
logging improved.
Enabled sliced_attention.
logging improved.
Enabled clip hacks.
cuda
cuda
No module 'xformers'. Proceeding without it.
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loaded model config from [./models/cldm_v15.yaml]
Loaded state_dict from [./models/control_any3_openpose.pth]
Running on local URL:  http://0.0.0.0:7861

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "F:\1\envs\control\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\1\envs\control\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "F:\1\envs\control\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\1\envs\control\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\1\envs\control\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\1\envs\control\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\ControlNet-main\gradio_canny2image.py", line 33, in process
    detected_map = apply_canny(img, low_threshold, high_threshold)
NameError: name 'apply_canny' is not defined

**Comment by FurkanGozukara** [comment]
I suggest you to use automatic1111 extension

This extension is a really big improvement over using native scripts

It works amazingly well and supports xformers as well now since automatic1111 supports

Also not anymore you need a merged ckpt files

It works with any custom model as well

16.) Automatic1111 Web UI
[Sketches into Epic Art with 1 Click: A Guide to Stable Diffusion ControlNet in Automatic1111 Web UI](https://www.youtube.com/watch?v=vhqqmkTBMlU) 
[![image](https://user-images.githubusercontent.com/19240467/218806127-c84d1ff8-d5bb-41b0-bdef-6922568792b9.png)
](https://www.youtube.com/watch?v=vhqqmkTBMlU)
