### ISSUE TITLE
Errno13

### ISSUE THREAD

**Issue by Horang1173** [lllyasviel/ControlNet#511]
I'm trying to run control net but am getting the following error
"
*** Error running process: H:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "H:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "H:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 731, in process
        model_net = Script.load_control_model(p, unet, unit.model, unit.low_vram)
      File "H:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 292, in load_control_model
        model_net = Script.build_control_model(p, unet, model, lowvram)
      File "H:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 375, in build_control_model
        network = network_module(
      File "H:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\adapter.py", line 73, in __init__
        self.config = OmegaConf.load(config_path)
      File "H:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\omegaconf\omegaconf.py", line 187, in load
        with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
    PermissionError: [Errno 13] Permission denied: 'H:\\Stable Diffusion\\stable-diffusion-webui\\extensions\\sd-webui-controlnet'
"
I've given full permissions to that folder to practically every program on the computer, but it still wont work. Any ideas?

**Comment by Horang1173** [comment]
I found out. How to fix it. Very mad at myself for this one... the .safetensors and .yaml files must have matching names. IT does not download like that. So yeah.
