### ISSUE TITLE
Bug endless loading of models

### ISSUE THREAD

**Issue by vanyvl** [lllyasviel/ControlNet#523]
<img width="561" alt="Безымянный" src="https://github.com/lllyasviel/ControlNet/assets/142838400/a6e10f9e-8e34-4564-944b-4841ac2d8121">

Traceback (most recent call last):
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 595, in filter_selected
    ) = global_state.select_control_type(k)
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 230, in select_control_type
    default_option = preprocessor_filters[control_type]
TypeError: unhashable type: 'list'
Traceback (most recent call last):
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 595, in filter_selected
    ) = global_state.select_control_type(k)
  File "G:\Programs\Stabel Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 230, in select_control_type
    default_option = preprocessor_filters[control_type]
TypeError: unhashable type: 'list'

**Comment by PublicClassHorny** [comment]
Same error, can anyone help?

**Comment by kaisalover97** [comment]
Same error here. The thing is, in the controlnet, all of properties are repeated. i think when i choose one of them, the value is a list and the error occurs. and yes it only happens in the new version (1.6)
![image](https://github.com/lllyasviel/ControlNet/assets/144237481/83943d39-f389-45b2-a556-a4022068f399)

**Comment by Rkkss** [comment]
Tried update and It didn't work ControlNet v1.1.408

**Comment by kaisalover97** [comment]
Deleting /venv worked for me too
![image](https://github.com/lllyasviel/ControlNet/assets/144237481/29cb3ea2-5876-4028-b355-cb2026aa73cd)

**Comment by art13eck** [comment]
Deleting /venv **not** work for me. With full reinstall automatic1111 work, but it doesn't suit me

**Comment by PublicClassHorny** [comment]
Oh sorry i forgot. I deleted venv folder first. Then i restarted UI , it downloaded some files automatically and then i updated all my extensions and restart UI again. Maybe that's the best decision to make it work for everyone

**Comment by tweenpix** [comment]
> Oh sorry i forgot. I deleted venv folder first. Then i restarted UI , it downloaded some files automatically and then i updated all my extensions and restart UI again. Maybe that's the best decision to make it work for everyone

ya, thanks. it's worked

**Comment by geroldmeisinger** [comment]
if this is an automatic1111 control net extension question, i think this belongs here https://github.com/Mikubill/sd-webui-controlnet/issues
