### ISSUE TITLE
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. 

### ISSUE THREAD

**Issue by theshi-1128** [lllyasviel/ControlNet#555]
(ls) liu@liu-System-Product-Name:~/ls/ControlNet-main$ python tool_add_control.py ./models/v1-5-pruned.ckpt ./models/control_sd15_ini.ckpt
logging improved.
No module 'xformers'. Proceeding without it.
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Traceback (most recent call last):
  File "/home/liu/ls/ControlNet-main/tool_add_control.py", line 27, in <module>
    model = create_model(config_path='./models/cldm_v15.yaml')
  File "/home/liu/ls/ControlNet-main/cldm/model.py", line 26, in create_model
    model = instantiate_from_config(config.model).cpu()
  File "/home/liu/ls/ControlNet-main/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/liu/ls/ControlNet-main/cldm/cldm.py", line 311, in __init__
    super().__init__(*args, **kwargs)
  File "/home/liu/ls/ControlNet-main/ldm/models/diffusion/ddpm.py", line 565, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/home/liu/ls/ControlNet-main/ldm/models/diffusion/ddpm.py", line 632, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/home/liu/ls/ControlNet-main/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/liu/ls/ControlNet-main/ldm/modules/encoders/modules.py", line 99, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(version)
  File "/home/liu/anaconda3/envs/ls/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2029, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

how can i fix it?

**Comment by hxwxss** [comment]
Maybe you can download the CLIP-vit-large-patch14 model from Hugging Face and then save it in the path './openai/'.

**Comment by theshi-1128** [comment]
Thanks a lot for your help！It does work.



发自我的iPhone


------------------ Original ------------------
From: Yuxuan Cheng ***@***.***&gt;
Date: Sat,Oct 21,2023 6:03 PM
To: lllyasviel/ControlNet ***@***.***&gt;
Cc: theshi-1128 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [lllyasviel/ControlNet] OSError: Can't load tokenizer for'openai/clip-vit-large-patch14'.  (Issue #555)





 
Maybe you can download the CLIP-vit-large-patch14 model from Hugging Face and then save it in the path './openai/'.

**Comment by Wei-1989** [comment]
> Maybe you can download the CLIP-vit-large-patch14 model from Hugging Face and then save it in the path './openai/'.

would you please tell me what models do i need?
and should I create a new folder named 'openai' in the root dictory?

**Comment by leejq666** [comment]
> Thanks a lot for your help！It does work. 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Yuxuan Cheng ***@***.***&gt; Date: Sat,Oct 21,2023 6:03 PM To: lllyasviel/ControlNet ***@***.***&gt; Cc: theshi-1128 ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [lllyasviel/ControlNet] OSError: Can't load tokenizer for'openai/clip-vit-large-patch14'. (Issue #555) Maybe you can download the CLIP-vit-large-patch14 model from Hugging Face and then save it in the path './openai/'. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Greetings! Could you elaborate on the procedure? I have downloaded the CLIP model and created a directory named 'openai/clip-vit-alrge-patch14'. I have placed the downloaded model within this directory, yet I continue to encounter errors.
