### ISSUE TITLE
AttributeError: 'ControlModel' object has no attribute 'reset' with AnimateDiff

### ISSUE THREAD

**Issue by binarypearl** [lllyasviel/ControlNet#631]
In Automatic1111 when I use AnimateDiff in combination with ControlNet I get the error below at the console.  It was working a few days prior, but started getting it when I updated ControlNet. Not 100% sure if this is a ControlNet or AnimateDiff issue, but wanted to post it here first.  If any questions or need additional information please let me know, thanks! 

```
*** Error running process: C:\Users\shaun\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Users\shaun\ai\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "C:\Users\shaun\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1117, in process
        self.controlnet_hack(p)
      File "C:\Users\shaun\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1102, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Users\shaun\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 248, in hacked_main_entry
        model_net.reset()
    AttributeError: 'ControlModel' object has no attribute 'reset'
```

**Comment by binarypearl** [comment]
Sorry, the recommendation I got from discord was to open this issue with sd-webui-controlnet project; I didn't notice that was a different project.  Closing this issue.
