### ISSUE TITLE
Unable to install gradio=3.40.1

### ISSUE THREAD

**Issue by cqhung1412** [lllyasviel/ControlNet#658]
Hi, I follow these issues https://github.com/lllyasviel/ControlNet/issues/579 and https://github.com/lllyasviel/ControlNet/issues/475#issuecomment-1649835292, I try to use `pip install gradio==3.40.1`, but it keeps running for a very long time (over 1 hour already) and it just stop progressing when reaching matplotlib

> INFO: pip is looking at multiple versions of contourpy to determine which version is compatible with other requirements. This could take a while.
  Using cached contourpy-1.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (269 kB)
INFO: pip is looking at multiple versions of matplotlib to determine which version is compatible with other requirements. This could take a while.
Collecting matplotlib~=3.0
  Using cached matplotlib-3.7.4-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.2 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Downloading matplotlib-3.7.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.2 MB)
     |████████████████████████████████| 9.2 MB 1.4 MB/s 

Does anyone have any alternative? I tried installing the latest version of gradio v4.21.0 but it shows this error instead

> Traceback (most recent call last):
  File "gradio_canny2image.py", line 74, in <module>
    input_image = gr.Image(source='upload', type="numpy")
  File "/root/anaconda3/envs/control/lib/python3.8/site-packages/gradio/component_meta.py", line 159, in wrapper
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'source'

Thank you in advance for your help.

**Comment by AAKillua** [comment]
I'm also having the same problem, pip install gradio==3.38.0, it's also very slow to download, and there is also a 'source' problem when i download the latest version. Have you solved it?

**Comment by elvinyychen** [comment]
Hi, try to upgrade your pip before installing gradio.
```
python -m pip install --upgrade pip
pip install gradio
```

**Comment by AAKillua** [comment]
Yes, I tried to update the pip version and can download graid successfully. Thank you very much for your reply.



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/19/2024 12:57 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [lllyasviel/ControlNet] Unable to install gradio=3.40.1 (Issue #658) |

Hi, try to upgrade your pip before installing gradio.

python -m pip install --upgrade pip
pip install gradio
