### ISSUE TITLE
Question about the environment

### ISSUE THREAD

**Issue by qiqiApink** [lllyasviel/ControlNet#691]
I followed your instructions to build the environment. But I got the following error when running tutorial_train.py:
```
Traceback (most recent call last):
  File "tutorial_train.py", line 1, in <module>
    from share import *
  File "/workspace/ControlNet/share.py", line 2, in <module>
    from cldm.hack import disable_verbosity, enable_sliced_attention
  File "/workspace/ControlNet/cldm/hack.py", line 5, in <module>
    import ldm.modules.attention
  File "/workspace/ControlNet/ldm/modules/attention.py", line 4, in <module>
    from torch._C import TorchDispatchMode
ImportError: cannot import name 'TorchDispatchMode' from 'torch._C' (/opt/conda/envs/control/lib/python3.8/site-packages/torch/_C.cpython-38-x86_64-linux-gnu.so)
```
And the details of my environment is as follows:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
absl-py                   2.1.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aiofiles                  24.1.0                   pypi_0    pypi
aiohttp                   3.9.5                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
albumentations            1.3.0                    pypi_0    pypi
altair                    5.3.0                    pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
antlr4-python3-runtime    4.8                      pypi_0    pypi
anyio                     4.4.0                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
backports-zoneinfo        0.2.1                    pypi_0    pypi
basicsr                   1.4.2                    pypi_0    pypi
blas                      1.0                         mkl    defaults
blinker                   1.8.2                    pypi_0    pypi
braceexpand               0.1.7                    pypi_0    pypi
brotli-python             1.0.9            py38h6a678d5_8    defaults
bzip2                     1.0.8                h5eee18b_6    defaults
ca-certificates           2024.7.2             h06a4308_0    defaults
cachetools                5.4.0                    pypi_0    pypi
certifi                   2024.7.4         py38h06a4308_0    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.1.7                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cudatoolkit               11.3.1               h2bc3f7f_2    defaults
cycler                    0.12.1                   pypi_0    pypi
dnspython                 2.6.1                    pypi_0    pypi
einops                    0.3.0                    pypi_0    pypi
email-validator           2.2.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
fastapi                   0.111.1                  pypi_0    pypi
fastapi-cli               0.0.4                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
ffmpy                     0.3.2                    pypi_0    pypi
filelock                  3.15.4                   pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0    defaults
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
ftfy                      6.2.0                    pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.43                   pypi_0    pypi
gmp                       6.2.1                h295c915_3    defaults
gnutls                    3.6.15               he1e5248_0    defaults
google-auth               2.32.0                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
gradio                    3.16.2                   pypi_0    pypi
grpcio                    1.64.1                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.5                    pypi_0    pypi
httptools                 0.6.1                    pypi_0    pypi
httpx                     0.27.0                   pypi_0    pypi
huggingface-hub           0.23.5                   pypi_0    pypi
idna                      3.7              py38h06a4308_0    defaults
imageio                   2.9.0                    pypi_0    pypi
imageio-ffmpeg            0.4.2                    pypi_0    pypi
importlib-metadata        8.0.0                    pypi_0    pypi
importlib-resources       6.4.0                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561    defaults
invisible-watermark       0.2.0                    pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jpeg                      9e                   h5eee18b_1    defaults
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
kornia                    0.6.0                    pypi_0    pypi
lame                      3.100                h7b6447c_0    defaults
lazy-loader               0.4                      pypi_0    pypi
lcms2                     2.12                 h3be6417_0    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
lerc                      3.0                  h295c915_0    defaults
libdeflate                1.17                 h5eee18b_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libiconv                  1.16                 h5eee18b_3    defaults
libidn2                   2.3.4                h5eee18b_0    defaults
libpng                    1.6.39               h5eee18b_0    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libtasn1                  4.19.0               h5eee18b_0    defaults
libtiff                   4.5.1                h6a678d5_0    defaults
libunistring              0.9.10               h27cfd23_0    defaults
libwebp-base              1.3.2                h5eee18b_0    defaults
linkify-it-py             2.0.3                    pypi_0    pypi
lmdb                      1.5.1                    pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_1    defaults
markdown                  3.6                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.7.5                    pypi_0    pypi
mdit-py-plugins           0.4.1                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640    defaults
mkl-service               2.4.0            py38h7f8727e_0    defaults
mkl_fft                   1.3.1            py38hd3c417c_0    defaults
mkl_random                1.2.2            py38h51133e4_0    defaults
multidict                 6.0.5                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    defaults
nettle                    3.7.3                hbbd107a_1    defaults
networkx                  3.1                      pypi_0    pypi
numpy                     1.23.1           py38h6c91a56_0    defaults
numpy-base                1.23.1           py38ha15fc14_0    defaults
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.1.1                    pypi_0    pypi
open-clip-torch           2.0.2                    pypi_0    pypi
opencv-contrib-python     4.3.0.36                 pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
openh264                  2.1.1                h4ff587b_0    defaults
openjpeg                  2.4.0                h9ca470c_2    defaults
openssl                   1.1.1w               h7f8727e_0    defaults
orjson                    3.10.6                   pypi_0    pypi
packaging                 24.1                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
pillow                    10.4.0           py38h5eee18b_0    defaults
pip                       20.3.3           py38h06a4308_0    defaults
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
prettytable               3.6.0                    pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
pyarrow                   17.0.0                   pypi_0    pypi
pyasn1                    0.6.0                    pypi_0    pypi
pyasn1-modules            0.4.0                    pypi_0    pypi
pycryptodome              3.20.0                   pypi_0    pypi
pydantic                  2.8.2                    pypi_0    pypi
pydantic-core             2.20.1                   pypi_0    pypi
pydeck                    0.9.1                    pypi_0    pypi
pydeprecate               0.3.1                    pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pympler                   1.1                      pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pysocks                   1.7.1            py38h06a4308_0    defaults
python                    3.8.5                h7579374_1    defaults
python-dateutil           2.9.0.post0              pypi_0    pypi
python-dotenv             1.0.1                    pypi_0    pypi
python-multipart          0.0.9                    pypi_0    pypi
pytorch                   1.12.1          py3.8_cuda11.3_cudnn8.3.2_0    pytorch
pytorch-lightning         1.5.0                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2024.1                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
qudida                    0.0.4                    pypi_0    pypi
readline                  8.2                  h5eee18b_0    defaults
referencing               0.35.1                   pypi_0    pypi
regex                     2024.5.15                pypi_0    pypi
requests                  2.32.2           py38h06a4308_0    defaults
requests-oauthlib         2.0.0                    pypi_0    pypi
rich                      13.7.1                   pypi_0    pypi
rpds-py                   0.19.0                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
safetensors               0.2.7                    pypi_0    pypi
scikit-image              0.20.0                   pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.9.1                    pypi_0    pypi
semver                    3.0.2                    pypi_0    pypi
setuptools                69.5.1           py38h06a4308_0    defaults
shellingham               1.5.4                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1    defaults
smmap                     5.0.1                    pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0    defaults
starlette                 0.37.2                   pypi_0    pypi
streamlit                 1.12.1                   pypi_0    pypi
streamlit-drawable-canvas 0.8.0                    pypi_0    pypi
tb-nightly                2.14.0a20230808          pypi_0    pypi
tensorboard               2.14.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
test-tube                 0.7.5                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2023.7.10                pypi_0    pypi
timm                      0.6.12                   pypi_0    pypi
tk                        8.6.14               h39e8969_0    defaults
tokenizers                0.12.1                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
torchmetrics              0.6.0                    pypi_0    pypi
torchvision               0.13.1               py38_cu113    pytorch
tornado                   6.4.1                    pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
transformers              4.19.2                   pypi_0    pypi
typer                     0.12.3                   pypi_0    pypi
typing_extensions         4.11.0           py38h06a4308_0    defaults
tzdata                    2024.1                   pypi_0    pypi
tzlocal                   5.2                      pypi_0    pypi
uc-micro-py               1.0.3                    pypi_0    pypi
urllib3                   2.2.2            py38h06a4308_0    defaults
uvicorn                   0.30.1                   pypi_0    pypi
uvloop                    0.19.0                   pypi_0    pypi
validators                0.33.0                   pypi_0    pypi
watchdog                  4.0.1                    pypi_0    pypi
watchfiles                0.22.0                   pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webdataset                0.2.5                    pypi_0    pypi
websockets                12.0                     pypi_0    pypi
werkzeug                  3.0.3                    pypi_0    pypi
wheel                     0.43.0           py38h06a4308_0    defaults
xz                        5.4.6                h5eee18b_1    defaults
yapf                      0.32.0                   pypi_0    pypi
yarl                      1.9.4                    pypi_0    pypi
zipp                      3.19.2                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1    defaults
zstd                      1.5.5                hc292b87_2    defaults
```
Can you give me some advice?

**Comment by atg93** [comment]
Hi, could you try these libraries ? I think they work. 

[req.txt](https://github.com/user-attachments/files/16282498/req.txt)

Package                       Version         Location
----------------------------- --------------- ---------------------------------------

-----------------------------------
absl-py                       0.9.0
accelerate                    0.25.0
addict                        2.4.0
aiofiles                      23.2.1
aiohttp                       3.7.4.post0
alabaster                     0.7.12
albumentations                1.3.0
altair                        5.2.0
annotated-types               0.6.0
antlr4-python3-runtime        4.8
anyio                         4.2.0
apex                          0.1
appdirs                       1.4.4
argh                          0.26.2
argon2-cffi                   20.1.0
ascii-graph                   1.5.1
asgiref                       3.3.4
astunparse                    1.6.3
async-generator               1.10
async-timeout                 3.0.1
atari-py                      0.2.6
attrs                         23.2.0
audioread                     2.1.9
autopep8                      1.5.4
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.zoneinfo            0.2.1
basicsr                       1.4.2
beautifulsoup4                4.7.1
beautifultable                0.7.0
bitsandbytes                  0.41.3.post2
bleach                        3.3.0
blinker                       1.4
blis                          0.7.4
boto                          2.49.0
boto3                         1.17.96
botocore                      1.20.96
box2d-py                      2.3.8
braceexpand                   0.1.7
brotlipy                      0.7.0
bs4                           0.0.2
bz2file                       0.98
cachetools                    4.1.0
carla                         0.9.13          /opt/conda/lib/python3.8/site-packages/carla-0.9.13-py3.7-linux-x86_64.egg
catalogue                     2.0.4
certifi                       2022.6.15.2
cffi                          1.14.0
chardet                       3.0.4
charset-normalizer            3.3.2
click                         7.1.2
cloudpickle                   1.3.0
codecov                       2.1.11
colorama                      0.4.4
conda                         4.10.1
conda-build                   3.21.4
conda-package-handling        1.7.3
configparser                  5.0.0
coverage                      5.5
cryptography                  2.9.2
cssselect                     1.2.0
cycler                        0.10.0
cymem                         2.0.5
Cython                        0.28.4
DataProperty                  0.50.1
datasets                      2.19.2
decorator                     4.4.2
defusedxml                    0.7.1
descartes                     1.1.0
dictor                        0.1.7
dill                          0.3.6
distro                        1.8.0
Django                        3.2
DLLogger                      0.1.0
dm-control                    0.0.312466143
dm-env                        1.2
dm-tree                       0.1.5
docker                        3.6.0
docker-pycreds                0.4.0
docutils                      0.16
einops                        0.3.0
entrypoints                   0.3
ephem                         3.7.7.1
evalai                        1.3.16
exceptiongroup                1.2.0
fake-useragent                1.5.1
fastapi                       0.108.0
ffmpy                         0.3.1
filelock                      3.0.12
filterpy                      1.4.5
flake8                        3.7.9
Flask                         2.0.1
flatbuffers                   2.0
fsspec                        2024.3.1
ftfy                          6.2.0
future                        0.18.2
gast                          0.3.3
gitdb                         4.0.5
GitPython                     3.1.7
glfw                          1.11.2
glob2                         0.7
google-api-core               2.19.0
google-auth                   1.35.0
google-auth-oauthlib          0.4.1
google-cloud-core             1.7.0
google-cloud-storage          1.38.0
google-crc32c                 1.1.2
google-pasta                  0.2.0
google-resumable-media        1.3.0
googleapis-common-protos      1.63.1
GPUtil                        1.4.0
gql                           0.2.0
gradio                        3.16.2
gradio-client                 0.7.2
graphql-core                  1.1
graphsurgeon                  0.4.5
grpcio                        1.27.2
gunicorn                      20.1.0
gym                           0.17.2
gym-notices                   0.0.8
h11                           0.14.0
h5py                          3.10.0
html2text                     2020.1.16
httpcore                      1.0.2
httptools                     0.2.0
httpx                         0.26.0
huggingface-cli               0.1
huggingface-hub               0.23.3
hydra-core                    1.1.0
hypothesis                    4.50.8
idna                          2.10
imageio                       2.9.0
imageio-ffmpeg                0.4.2
imagesize                     1.2.0
imgaug                        0.4.0
importlib-metadata            1.7.0
importlib-resources           6.4.0
inflect                       5.3.0
iniconfig                     1.1.1
inquirerpy                    0.3.4
invisible-watermark           0.2.0
ipdb                          0.13.9
ipykernel                     5.3.4
ipython                       7.17.0
ipython-genutils              0.2.0
itsdangerous                  2.0.1
jedi                          0.17.2
Jinja2                        3.0.1
jmespath                      0.10.0
joblib                        1.0.1
json5                         0.9.5
jsonschema                    3.2.0
jupyter-client                6.1.6
jupyter-core                  4.6.3
jupyter-tensorboard           0.2.0
jupyterlab                    2.3.1
jupyterlab-pygments           0.1.2
jupyterlab-server             1.2.0
jupytext                      1.11.3
Keras-Preprocessing           1.1.0
kiwisolver                    1.2.0
kornia                        0.6.0
libarchive-c                  3.1
librosa                       0.8.0
linkify-it-py                 2.0.3
llvmlite                      0.35.0
lmdb                          1.2.1
lxml                          4.6.2
Mako                          1.1.4
Markdown                      3.2.2
markdown-it-py                3.0.0
MarkupSafe                    2.0.1
maskrcnn-benchmark            0.1
matplotlib                    3.3.1
matplotlib-inline             0.1.2
mbstrdecoder                  1.0.1
mccabe                        0.6.1
mdit-py-plugins               0.2.8
mdurl                         0.1.2
mistune                       0.8.4
mlperf-compliance             0.0.10
mock                          4.0.3
moviepy                       1.0.1
mpi4py                        3.0.3
msgfy                         0.1.0
multidict                     5.1.0
multiprocess                  0.70.14
murmurhash                    1.0.5
nbclient                      0.5.3
nbconvert                     6.0.7
nbformat                      5.1.3
nest-asyncio                  1.5.1
networkx                      2.4
nltk                          3.6.2
notebook                      6.2.0
numba                         0.52.0
numpy                         1.23.1
nvidia-dali-cuda110           1.2.0
nvidia-dlprof-pytorch-nvtx    1.2.0
nvidia-dlprofviewer           1.2.0
nvidia-ml-py3                 7.352.0
oauthlib                      3.1.0
olefile                       0.46
omegaconf                     2.1.1
onnx                          1.8.0
onnxruntime                   1.8.0
open-clip-torch               2.0.2
openai                        0.28.0
opencv-contrib-python         4.3.0.36
opencv-python                 4.5.1.48
opencv-python-headless        4.10.0.84
openprompt                    1.0.1
opt-einsum                    3.2.1
orjson                        3.9.10
outcome                       1.3.0.post0
packaging                     23.2
pandas                        1.1.0
pandocfilters                 1.4.3
parse                         1.20.2
parso                         0.7.0
pathtools                     0.1.2
pathvalidate                  2.4.1
pathy                         0.5.2
pexpect                       4.8.0
pfzy                          0.3.4
pickleshare                   0.7.5
Pillow                        10.1.0
Pillow-SIMD                   7.0.0.post3
pip                           20.2.2
pkginfo                       1.7.0
pluggy                        0.13.1
polygraphy                    0.30.2
pooch                         1.4.0
preshed                       3.0.5
prettytable                   3.6.0
proglog                       0.1.9
progressbar                   2.5
prometheus-client             0.11.0
promise                       2.3
prompt-toolkit                3.0.5
proto-plus                    1.23.0
protobuf                      3.20.1
psutil                        5.7.2
ptyprocess                    0.6.0
py                            1.10.0
py-trees                      0.8.3
pyarrow                       16.1.0
pyarrow-hotfix                0.6
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pybind11                      2.6.2
pycocotools                   2.0+nv0.5.1
pycodestyle                   2.6.0
pycosat                       0.6.3
pycparser                     2.20
pycryptodome                  3.20.0
pycuda                        2020.1
pydantic                      2.5.2
pydantic-core                 2.14.5
pydeck                        0.9.1
pyDeprecate                   0.3.1
pydot                         1.4.1
pydub                         0.25.1
pyee                          11.1.0
pyflakes                      2.1.1
pygame                        2.0.0
pygccxml                      2.0.1
pygments                      2.17.2
PyJWT                         1.7.1
Pympler                       1.1
pynvml                        8.0.4
PyOpenGL                      3.1.5
pyOpenSSL                     19.1.0
pyparsing                     2.4.7
pyplusplus                    1.8.4
pyppeteer                     2.0.0
PyPrind                       2.11.3
pyquery                       2.0.0
pyrsistent                    0.17.3
PySocks                       1.7.1
pytablewriter                 0.47.0
pytest                        6.2.4
pytest-cov                    2.12.1
pytest-pythonpath             0.7.3
python-dateutil               2.8.1
python-dotenv                 0.17.1
python-hostlist               1.21
python-multipart              0.0.6
python-nvd3                   0.15.0
python-slugify                5.0.2
pytools                       2021.2.7
pytorch-lightning             1.6.4
pytorch-quantization          2.1.0
pytorch-transformers          1.1.0
pytz                          2020.1
pyu2f                         0.1.5
PyWavelets                    1.1.1
PyYAML                        6.0.1
pyzmq                         19.0.1
qudida                        0.0.4
rdp                           0.8
regex                         2021.4.4
requests                      2.25.1
requests-html                 0.10.0
requests-oauthlib             1.3.0
resampy                       0.2.2
responses                     0.18.0
revtok                        0.0.3
rich                          13.7.0
rouge                         1.0.0
rsa                           4.0
ruamel-yaml-conda             0.15.80
s3transfer                    0.4.2
sacrebleu                     1.2.10
sacremoses                    0.0.35
safetensors                   0.2.7
scikit-image                  0.17.2
scikit-learn                  0.24.2
scipy                         1.4.1
selenium                      4.17.0
semantic-version              2.10.0
semver                        3.0.2
Send2Trash                    1.5.0
sentencepiece                 0.1.99
sentry-sdk                    0.16.5
setuptools                    59.5.0
Shapely                       1.7.0
shellingham                   1.4.0
shortuuid                     1.0.1
six                           1.15.0
smart-open                    2.2.1
smmap                         3.0.4
sniffio                       1.3.0
snowballstemmer               2.1.0
sortedcontainers              2.4.0
SoundFile                     0.10.3.post1
soupsieve                     2.0.1
sox                           1.4.1
spacy                         3.0.6
spacy-legacy                  3.0.6
Sphinx                        4.0.2
sphinx-glpi-theme             0.3
sphinx-rtd-theme              0.5.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
sqlparse                      0.4.1
srsly                         2.4.1
srunner                       0.15
stable-baselines3             0.8.0
starlette                     0.32.0.post1
streamlit                     1.12.1
streamlit-drawable-canvas     0.8.0
subprocess32                  3.5.4
subword-nmt                   0.3.3
swig                          4.0.2
tabledata                     1.1.4
tabulate                      0.8.7
tb-nightly                    2.14.0a20230808
tensorboard                   2.2.1
tensorboard-data-server       0.7.2
tensorboard-plugin-wit        1.6.0.post3
tensorboardX                  2.5.1
tensorflow                    2.2.0
tensorflow-estimator          2.2.0
tensorrt                      7.2.3.4
termcolor                     1.1.0
terminado                     0.10.1
test-tube                     0.7.5
testpath                      0.5.0
text-unidecode                1.3
thinc                         8.0.3
threadpoolctl                 2.1.0
tifffile                      2020.10.1
timm                          0.6.12
tokenizers                    0.12.1
toml                          0.10.1
tomlkit                       0.12.0
toolz                         0.12.0
torch                         1.12.1
torchmetrics                  0.6.0
torchtext                     0.12.0
torchvision                   0.13.1
tornado                       6.0.4
tqdm                          4.66.4
traitlets                     4.3.3
transformers                  4.19.2
transforms3d                  0.4.1
trio                          0.25.1
trio-websocket                0.11.1
typepy                        1.1.5
typer                         0.9.0
typing-extensions             4.9.0
tzlocal                       5.2
uc-micro-py                   1.0.3
uff                           0.6.9
Unidecode                     1.2.0
urllib3                       1.26.1
uvicorn                       0.14.0
uvloop                        0.15.2
validators                    0.12.6
w3lib                         2.2.1
wandb                         0.10.12
wasabi                        0.8.2
watchdog                      0.10.3
watchgod                      0.7
wcwidth                       0.2.5
webcolors                     1.13
webdataset                    0.2.5
webencodings                  0.5.1
websocket-client              1.8.0
websockets                    10.4
Werkzeug                      1.0.1
wheel                         0.34.2
whitenoise                    5.2.0
wrapt                         1.12.1
wsproto                       1.2.0
xxhash                        3.1.0
yacs                          0.1.8
yapf                          0.32.0
yarl                          1.5.1
zipp                          3.1.0

**Comment by atg93** [comment]
I think I can run tutorial_train.py with these libraries. I hope they will work for you too.

[req.txt](https://github.com/user-attachments/files/16282636/req.txt)

**Comment by AndySyd** [comment]
Thanks god, this Issue solved my error perfectly. Highly recommend that set pytorch_lightning==1.5.0 !!! otherwise it will raise error about missing dataloader_idx.
