### ISSUE TITLE
RuntimeError: Failed to import transformers.models.t5.modeling_t5 because of the following error (look up to see its traceback): Failed to import transformers.onnx.config because of the following error (look up to see its traceback): DLL load failed while importing _imaging: The specified module could not be found.

### ISSUE THREAD

**Issue by jiajiao272727** [lllyasviel/ControlNet#716]
I am trying to train ControlNet following [https://github.com/lllyasviel/ControlNet/blob/main/docs/train.md](url), but stuck in step 3 with this error. May I ask does anyone knows how to solve it? Thank you so much!

`(control) PS D:\experiment\ControlNet> python tool_add_control_sd21.py ./models/v2-1_512-ema-pruned.ckpt ./models/control_sd21_ini.ckpt
Traceback (most recent call last):
  File "C:\Users\.conda\envs\control\lib\site-packages\transformers\utils\import_utils.py", line 1130, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\.conda\envs\control\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\.conda\envs\control\lib\site-packages\transformers\onnx\config.py", line 36, in <module>
    from PIL import Image
  File "C:\Users\.conda\envs\control\lib\site-packages\PIL\Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\.conda\envs\control\lib\site-packages\transformers\utils\import_utils.py", line 1130, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\.conda\envs\control\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\.conda\envs\control\lib\site-packages\transformers\models\t5\modeling_t5.py", line 50, in <module>
    from .configuration_t5 import T5Config
  File "C:\Users\.conda\envs\control\lib\site-packages\transformers\models\t5\configuration_t5.py", line 19, in <module>
    from ...onnx import OnnxSeq2SeqConfigWithPast
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "C:\Users\.conda\envs\control\lib\site-packages\transformers\utils\import_utils.py", line 1120, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\.conda\envs\control\lib\site-packages\transformers\utils\import_utils.py", line 1132, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.onnx.config because of the following error (look up to see its traceback):
DLL load failed while importing _imaging: The specified module could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\experiment\ControlNet\tool_add_control_sd21.py", line 14, in <module>
    from share import *
  File "D:\experiment\ControlNet\share.py", line 2, in <module>
    from cldm.hack import disable_verbosity, enable_sliced_attention
  File "D:\experiment\ControlNet\cldm\hack.py", line 4, in <module>
    import ldm.modules.encoders.modules
  File "D:\experiment\ControlNet\ldm\modules\encoders\modules.py", line 5, in <module>
    from transformers import T5Tokenizer, T5EncoderModel, CLIPTokenizer, CLIPTextModel
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "C:\Users\.conda\envs\control\lib\site-packages\transformers\utils\import_utils.py", line 1121, in __getattr__
    value = getattr(module, name)
  File "C:\Users\.conda\envs\control\lib\site-packages\transformers\utils\import_utils.py", line 1120, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\.conda\envs\control\lib\site-packages\transformers\utils\import_utils.py", line 1132, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.t5.modeling_t5 because of the following error (look up to see its traceback):
Failed to import transformers.onnx.config because of the following error (look up to see its traceback):
DLL load failed while importing _imaging: The specified module could not be found.`

**Comment by jiajiao272727** [comment]
conda update Pillow
