### ISSUE TITLE
dejaju sans font

### ISSUE THREAD

**Issue by jrmylee** [lllyasviel/ControlNet#90]
I'm not able to train because the sans font isn't included. Any suggestions on where to get this file?

Epoch 0:   0%|                                                                                                  | 0/12500 [00:00<?, ?it/s]/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py:56: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  warning_cache.warn(
Traceback (most recent call last):
  File "tutorial_train.py", line 35, in <module>
    trainer.fit(model, dataloader)
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in fit
    self._call_and_handle_interrupt(
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1193, in _run
    self._dispatch()
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1272, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1282, in run_stage
    return self._run_train()
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1312, in _run_train
    self.fit_loop.run()
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 220, in advance
    self.trainer.call_hook("on_train_batch_end", batch_end_outputs, batch, batch_idx, **extra_kwargs)
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1477, in call_hook
    callback_fx(*args, **kwargs)
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py", line 179, in on_train_batch_end
    callback.on_train_batch_end(self, self.lightning_module, outputs, batch, batch_idx, 0)
  File "/home/engineering/ControlNet/cldm/logger.py", line 76, in on_train_batch_end
    self.log_img(pl_module, batch, batch_idx, split="train")
  File "/home/engineering/ControlNet/cldm/logger.py", line 55, in log_img
    images = pl_module.log_images(batch, split=split, **self.log_images_kwargs)
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/engineering/ControlNet/cldm/cldm.py", line 356, in log_images
    log["conditioning"] = log_txt_as_img((512, 512), batch[self.cond_stage_key], size=16)
  File "/home/engineering/ControlNet/ldm/util.py", line 19, in log_txt_as_img
    font = ImageFont.truetype('data/DejaVuSans.ttf', size=size)
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/PIL/ImageFont.py", line 1006, in truetype
    return freetype(font)
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/PIL/ImageFont.py", line 1003, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/engineering/miniconda3/envs/control/lib/python3.8/site-packages/PIL/ImageFont.py", line 253, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by Mikubill** [comment]
related: https://github.com/lllyasviel/ControlNet/issues/84#issuecomment-1434147318

**Comment by lllyasviel** [comment]
see if fixed https://github.com/lllyasviel/ControlNet/commit/31c4095c070efb7fbd8a95d808108ea75937ca5c

**Comment by jrmylee** [comment]
thank you!
